image: charlieharutaka/cetacea:latest

stages:
- install
- test
- deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - ./node_modules

install:
  stage: install
  script:
  - npm i

test:
  stage: test
  script:
  - npm test

lint:
  stage: test
  script:
  - npm run lint
  

deploy:
  stage: deploy
  only:
  - master
  script:
  - echo "No deployment yet"